// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskAgent.Infrastructure.Data;

#nullable disable

namespace TaskAgent.Infrastructure.Migrations.ConversationDb
{
    [DbContext(typeof(ConversationDbContext))]
    [Migration("20251126173145_AddConversationMessages")]
    partial class AddConversationMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskAgent.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz");

                    b.HasKey("MessageId");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("IX_ConversationMessages_ThreadId");

                    b.HasIndex("ThreadId", "Timestamp")
                        .HasDatabaseName("IX_ConversationMessages_ThreadId_Timestamp");

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("TaskAgent.Domain.Entities.ConversationThreadMetadata", b =>
                {
                    b.Property<string>("ThreadId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Preview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SerializedState")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("ThreadId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ConversationThreads_IsActive");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_ConversationThreads_UpdatedAt");

                    b.HasIndex("IsActive", "UpdatedAt")
                        .HasDatabaseName("IX_ConversationThreads_IsActive_UpdatedAt");

                    b.ToTable("ConversationThreads", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
